export const GET_BREEDS = 'GET_BREEDS';
export const GET_BREEDS_SUCCESS = 'GET_BREEDS_SUCCESS';
export const GET_BREED_IMAGES = 'GET_BREED_IMAGES';
export const GET_BREED_IMAGES_SUCCESS = 'GET_BREED_IMAGES_SUCCESS';

